/**
 * The relevance test harness: runs the pre-registered query manifest against the live index and
 * captures both the results and the ranking evidence behind them.
 *
 * The evidence is the point. Algolia ranks by an ordered tie-breaking formula, so "this result is
 * wrong" is only actionable once you know which criterion put it there — `getRankingInfo` turns a
 * disagreement about relevance into a fact you can read off the table.
 */
import { readFileSync } from 'node:fs';

import { client, indexName } from './algolia.js';
import { paths } from './paths.js';
import type { RestaurantRecord } from './record.js';

/** Deep enough to show what a diner actually sees above the fold, shallow enough to read. */
export const TOP_N = 5;

export interface TestQuery {
  id: string;
  category: string;
  query: string;
  /** What a good result looks like, written before any result was observed. */
  expect: string;
}

interface QueryManifest {
  about: string;
  notes: string[];
  queries: TestQuery[];
}

/** One hit, flattened to what the report shows and nothing more. */
export interface CapturedHit {
  rank: number;
  name: string;
  where: string;
  cuisine: string;
  stars: number;
  reviews: number;
  bayesian: number;
  popularity: number;
  /** Straight from `_rankingInfo` — the criteria that decided this row's position. */
  typos: number;
  exactWords: number;
  proximity: number;
  words: number;
}

export interface QueryResult {
  query: TestQuery;
  nbHits: number;
  processingTimeMS: number;
  hits: CapturedHit[];
}

export function loadQueries(): TestQuery[] {
  const manifest = JSON.parse(readFileSync(paths.relevanceQueries, 'utf8')) as QueryManifest;
  return manifest.queries;
}

export async function runQuery(query: TestQuery): Promise<QueryResult> {
  const response = await client.searchSingleIndex<RestaurantRecord>({
    indexName,
    searchParams: { query: query.query, hitsPerPage: TOP_N, getRankingInfo: true },
  });

  return {
    query,
    nbHits: response.nbHits ?? 0,
    processingTimeMS: response.processingTimeMS ?? 0,
    hits: response.hits.map((hit, index) => ({
      rank: index + 1,
      name: hit.name,
      where: `${hit.city}, ${hit.state}`,
      cuisine: hit.food_type,
      stars: hit.stars_count,
      reviews: hit.reviews_count,
      bayesian: hit.bayesian_rating,
      popularity: hit.popularity_score,
      typos: hit._rankingInfo?.nbTypos ?? 0,
      exactWords: hit._rankingInfo?.nbExactWords ?? 0,
      proximity: hit._rankingInfo?.proximityDistance ?? 0,
      words: hit._rankingInfo?.words ?? 0,
    })),
  };
}

export function formatReport(
  label: string,
  description: string,
  results: QueryResult[],
  settings: unknown,
  capturedOn: string,
): string {
  const lines: string[] = [
    `# Relevance — ${label}`,
    '',
    `Generated by \`npm run index:test -- ${label}\` on ${capturedOn}, against index ` +
      `\`${indexName}\` holding 5,000 restaurants.`,
    '',
    description,
    '',
    'Queries come from [`relevance-queries.json`](relevance-queries.json), which was written ' +
      'before any search result was observed. The `typos`, `exact`, `prox` and `words` columns ' +
      'are read straight from `_rankingInfo`: they are the criteria that decided each row, in ' +
      'formula order.',
    '',
    '<details><summary>Index settings at capture time</summary>',
    '',
    '```json',
    JSON.stringify(settings, null, 2),
    '```',
    '',
    '</details>',
    '',
    '## Summary',
    '',
    '| # | Query | Category | Hits | Top result |',
    '|---|---|---|---|---|',
  ];

  results.forEach((result, index) => {
    const top = result.hits[0];
    lines.push(
      `| ${index + 1} | ${formatQuery(result.query.query)} | ${result.query.category} | ` +
        `${result.nbHits.toLocaleString()} | ${top ? escapePipes(top.name) : '—'} |`,
    );
  });

  lines.push('', '## Results', '');

  results.forEach((result, index) => {
    lines.push(
      `### ${index + 1}. ${formatQuery(result.query.query)} — ${result.query.category}`,
      '',
      `**Looking for:** ${result.query.expect}`,
      '',
      `**${result.nbHits.toLocaleString()} hits** in ${result.processingTimeMS} ms.`,
      '',
    );

    if (result.hits.length === 0) {
      lines.push('No results.', '');
      return;
    }

    lines.push(
      '| # | Restaurant | Where | Cuisine | Rating | typos | exact | prox | words | bayes / pop |',
      '|---|---|---|---|---|---|---|---|---|---|',
    );
    for (const hit of result.hits) {
      lines.push(
        `| ${hit.rank} | ${escapePipes(hit.name)} | ${escapePipes(hit.where)} | ` +
          `${escapePipes(hit.cuisine)} | ${hit.stars.toFixed(1)}★ ${hit.reviews.toLocaleString()} | ` +
          `${hit.typos} | ${hit.exactWords} | ${hit.proximity} | ${hit.words} | ` +
          `${hit.bayesian.toFixed(1)} / ${hit.popularity} |`,
      );
    }
    lines.push('');
  });

  return `${lines.join('\n')}\n`;
}

/** The empty query is a real test case, so it needs a visible rendering rather than an empty cell. */
function formatQuery(query: string): string {
  return query === '' ? '_(empty query)_' : `\`${query}\``;
}

/** A pipe in a restaurant name would silently break the markdown table it sits in. */
function escapePipes(value: string): string {
  return value.replaceAll('|', '\\|');
}
